name: jupytergis-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - nodejs
  - hatch
  - jupyterlite-core
  - jupyterlite-xeus>=3.1.3,<4
  - jupyterlite-sphinx
  - sphinx
  - sphinx-tabs
  - pydata-sphinx-theme
  - sphinx-autodoc-typehints
  - sphinx-exercise
  - sphinx-togglebutton
  - myst-parser
  - xeus-python # TODO: Do we need this?
  - pip:
      - jupyterlab==4.3
      - datamodel-code-generator>=0.23.0
